### ISSUE TITLE
Priority/Importance of Meeting Invite using Direct Send is not working

### ISSUE THREAD

**Issue by deepika791** [microsoft/notification-provider#50]
**Describe the bug**
when we provide the priority of  meeting invite as the input to queue/send request, it is not sending the invites with the expected priority

**To Reproduce**
what ever the priority we set in the request input, the invite is received with normal priority

**Expected behavior**
The priority is as follows : High:0, low:1, normal:2 when priority is set to those values, the email should be delivered corresponding to the given priority.

**Screenshots**

**Additional context**

**Comment by sanjayprajap** [comment]
issue fixed
