### ISSUE TITLE
Status of emails remain as "Queued" if Service Account password is incorrect

### ISSUE THREAD

**Issue by patrickCode** [microsoft/notification-provider#96]
**Describe the bug**
The status of the email doesn't get updated to 'Failed' when mail fails due to incorrect Service Account password

**To Reproduce**
1. Set an incorrect password for the service account
2. Queue an email
3. Mail won't be sent but status will be shown as 'Queued'

**Expected behavior**
The status of the mail must be updated to 'Failed'

**Comment by sanjayprajap** [comment]
fixed in pull req #97
